// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
config({ quiet: true });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pgbouncer) connection.
    // The app itself connects via DATABASE_URL (pooled) — see src/lib/prisma.ts
    url: process.env["DIRECT_URL"],
  },
});
